server.port=${PORT:8080}

# lgging
logging.level.org.atmosphere = warn
logging.level.com.github.yuri0x7c1.bali=debug

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#spring.datasource.url=jdbc:postgresql://localhost:5432/bali_demo_app
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.hibernate.ddl-auto=update

spring.mustache.check-template-location = false

# This is a workaround for https://github.com/vaadin/spring/issues/381
spring.servlet.multipart.enabled = false

# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin.whitelisted-packages= com/github/yuri0x7c1/bali
